# Generated by Django 3.2 on 2021-05-21 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='crateDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
